spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    main: queue
    dlq: dlq
  exchange:
    main: exchange
    dlq: dlExchange
  routing:
    key: routingKey
    dlKey: dlRoutingKey