spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 5
          max-interval: 10s
          multiplier: 2

rabbitmq:
  queue:
    main: queue
    dlq: dlq
  exchange:
    main: exchange
    dlq: dlExchange
  routing:
    key: routingKey
    dlKey: dlRutingKey