spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: queueName
  exchange:
    name: exchangeName
  routing:
    key: routingKeyName