spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 3
          max-interval: 10s
          multiplier: 2

rabbitmq:
  queue:
    name: testQueue
  exchange:
    name: testExchange
  routing:
    key: testRoutingKey